"""add role to user and remove last_login

Revision ID: 87e671161dc3
Revises: 46535e43a5b4
Create Date: 2024-08-06 10:58:19.271739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87e671161dc3'
down_revision: Union[str, None] = '46535e43a5b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.String(), nullable=True))
    op.drop_column('users', 'last_login')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_login', sa.DATETIME(), nullable=True))
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
