
#: import Home views.home.Home
#: import Auth views.auth.Auth

<MainWindow>:
    orientation: 'vertical'
    canvas.before:
        Color:
            rgba: app.color_primary_bg
        Rectangle:
            pos: self.pos
            size: self.size
    ScreenManager:
        id: scrn_mngr
        Screen:
            name: 'scrn_auth'
            Auth:
                id: auth
        Screen:
            name: 'scrn_home'
            Home:
                id: home
